services:
  - type: web
    name: backend
    env: node
    build:
      pythonVersion: 3.10
    buildCommand: ./build.sh && npm install
    startCommand: node server.js
    region: oregon
    plan: free
